### ISSUE TITLE
Theme changes when login is unsuccessful

### ISSUE THREAD

**Issue by SUP3RIA** [Azareal/Gosora#1]
Chosen theme seems to fall back to default theme when login is unsuccessful .

Login: https://gosora-project.com/accounts/login/
Unsuccesful referral: https://gosora-project.com/accounts/login/submit/

**Comment by Azareal** [comment]
Hmmmm, I'll probably bounce an AJAX error back at the user at some point, maybe in the alpha phase.
I began adding per-route state to the not found page, but it might be tricky with the other ones, as the state might contaminate the error logic and cause an error in an error, unlikely but possible.

Still, I'll consider adding per-route state to them all.
