### ISSUE TITLE
Linux-Install Error

### ISSUE THREAD

**Issue by SUP3RIA** [Azareal/Gosora#3]
`Creating the admin user
Error 1364: Field 'oldestItemLikedCreatedAt' doesn't have a default value
Aborting installation...`

**Comment by SUP3RIA** [comment]
Ok, SQL has to be in unstrict mode.

**Comment by Azareal** [comment]
Yeah, MySQL can be a little fussy, I've noted that down, although it seems to work on my machine and this is the one where I usually get errors like that.

**Comment by wtl420** [comment]
I just encountered this same error. Looks like I had to disable `STRICT_TRANS_TABLES` in my `sql_mode`; my guess that's something Fedora has set for MariaDB by default.

**Comment by Azareal** [comment]
https://github.com/Azareal/Gosora/issues/40 One thing which might help to solve this is Docker, that doesn't work quite yet though.

I'll see if I can hunt down that specific setting and see what I can wrangle to get rid of this problem.
Unfortunately, Travis doesn't seem to set that flag for the database for the automated tests, so it's easy for this slip through.

**Comment by wtl420** [comment]
I saw this was closed and gave this a shot with `STRICT_TRANS_TABLES` enabled and got this new error:

```
Executing query #33
INSERT INTO `menu_items`(`mid`,`htmlID`,`cssClass`,`position`,`tmplName`,`order`) VALUES (1,'general_alerts','menu_alerts','right','menu_alerts',2);                                         
Error 1364: Field 'name' doesn't have a default value
Aborting installation...
```

If I disable it again, the install goes through fine, so I believe there's a few more queries that don't play nice with this.

**Comment by Azareal** [comment]
@wtl420 It should work now.
