### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by asminozhka** [Azareal/Gosora#53]
I frequently have errors
![image](https://user-images.githubusercontent.com/41116859/60809038-597a5f80-a192-11e9-8cdc-3e391c6a80ed.png)

First error (http: superfluous) is creates absolutely always
Second (crash) creates sometimes when i do nothing

**Comment by Azareal** [comment]
What version of Go are you using?

**Comment by asminozhka** [comment]
> What version of Go are you using?

1.12.6
