### ISSUE TITLE
Moving from net/http to fasthttp?

### ISSUE THREAD

**Issue by asminozhka** [Azareal/Gosora#55]
Fasthttp is much faster than net/http, so perfomance of the Gosora might became much bigger
https://github.com/valyala/fasthttp#switching-from-nethttp-to-fasthttp

**Comment by Azareal** [comment]
I don't think FastHTTP supports HTTP/2, only HTTP/1.1

**Comment by asminozhka** [comment]
Oh really... Then sorry for waste issue!
