### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by asminozhka** [Azareal/Gosora#59]
If that is available, how can i add favicon?
If that isn't available, please make it possible to add a favicon 😜

**Comment by Azareal** [comment]
You put a file called favicon.ico in /public/

**Comment by asminozhka** [comment]
[favicon.zip](https://github.com/Azareal/Gosora/files/3389141/favicon.zip)
So, i added a favicon.ico into /public/ and it is not working
![image](https://user-images.githubusercontent.com/41116859/61175668-19651380-a5bc-11e9-9f3e-900fe81bcdff.png)

And i have this error
![image](https://user-images.githubusercontent.com/41116859/61175670-1ff38b00-a5bc-11e9-9bb9-581d21037475.png)
![image](https://user-images.githubusercontent.com/41116859/61175671-23871200-a5bc-11e9-8165-3e818624dfa2.png)
`ERR_CONTENT_LENGTH_MISMATCH`

And nothing in the console

**Comment by asminozhka** [comment]
This works
![image](https://user-images.githubusercontent.com/41116859/61175738-2e8e7200-a5bd-11e9-9059-6dc8a681a51e.png)
![image](https://user-images.githubusercontent.com/41116859/61175740-3221f900-a5bd-11e9-992f-74bc2ba80eb0.png)

**Comment by Azareal** [comment]
Weird, I'll have to see what's causing that.
