### ISSUE TITLE
Questions about security

### ISSUE THREAD

**Issue by asminozhka** [Azareal/Gosora#60]
Is Gosora really safe in context of XSS attacks? Is username, replies, titles "defended"?

Does Gosora have CSRF protection?

**Comment by Azareal** [comment]
I'm still rolling it out but I have a content security policy header which shuts down any scripts which shouldn't be running. I'm still expanding it across the control panel however. Usernames, replies, titles, etc. should be escaped accordingly to deal with XSS. I will likely tighten the CSP further once it's fully in place to try to further guard against weird edge cases.

https://www.netsparker.com/blog/web-security/same-site-cookie-attribute-prevent-cross-site-request-forgery/
To deal with CSRF, I primarily use SameSite cookies which are supported by Firefox and Chrome. It is a new feature which was implemented in Firefox, I believe, a couple of years ago. There is also a token sent with requests which messes with other sites trying to mount CSRF attacks, although I may harden this further.
