### ISSUE TITLE
undefined: H_topic_reply_row_assign_hook

### ISSUE THREAD

**Issue by tuoling805** [Azareal/Gosora#74]
go run main.go
# github.com/Azareal/Gosora/common
common\routes_common.go:70:16: undefined: H_forum_check_pre_perms_hook
common\topic.go:850:3: undefined: H_topic_reply_row_assign_hook
common\topic.go:876:4: undefined: H_topic_reply_row_assign_hook

**Comment by Azareal** [comment]
Sorry, the installation process is a bit more involved than simply using `go run`.

https://github.com/Azareal/Gosora/blob/master/README.md

https://github.com/Azareal/Gosora/blob/master/docs/installation.md
